services:
  g1_upperbody_ros2:
    image: g1_upperbody_ros2:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: g1_upperbody_ros2
    network_mode: host
    privileged: true
    runtime: nvidia
    environment:
      DISPLAY: ${DISPLAY}
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes: 
    - /tmp/.X11-unix:/tmp/.X11-unix
    - ../src:/workspace/ros2_ws/src
    - /dev:/dev
    - /run/udev:/run/udev:ro
    stdin_open: true
    tty: true
